Feature: AddFruit - Add new fruit to inventory

  Background:
    Given I have the "FruitAPI" service initialized

  Scenario Outline: AddFruit endpoint tests with comprehensive validations
    When I create a POST request to "AddFruit" endpoint with test case "<tcNo>" query params "<queryParams>" headers "<headers>" with payload <payload>
    Then I receive a response with HTTP status code "<statusCode>" with status text "<statusText>"
    And I verify the "<fieldName>" from the response to be "<fieldValue>"
    And I verify the "<fieldToContain>" from the response to contain "<containsValue>"
    And I verify the headers "<expectedHeaders>" to be present
    And I verify the header value for the key "<headerKey>" to be "<headerValue>"
    And I verify the "<fieldExists>" in the response "exists"
    And I verify the "<fieldNotExists>" in the response "does not exist"
    And I verify the "<fieldType>" type in the response to be a "<expectedType>"
    And the response returned should match the schema "<schemaFile>"

    Examples:
      | tcNo  | description                                  | queryParams                | headers                       | payload                         | statusCode | statusText | fieldName | fieldValue | fieldToContain    | containsValue | expectedHeaders                | headerKey    | headerValue      | fieldExists       | fieldNotExists | fieldType   | expectedType | schemaFile           |
      | FA001 | Add mango - seasonal yellow                  | type=seasonal&color=yellow | none                          | add-fruit-payload.json          | 201        | Created    | status    | success    | message           | added         | Content-Type,X-Fruit-Id        | Content-Type | application/json | id                | password       | id          | string       | add-fruit-schema.json|
      | FA002 | Add mango - verify name exact match          | type=seasonal&color=yellow | none                          | add-fruit-payload.json          | 201        | Created    | name      | Mango      | scientificName    | Mangifera     | Content-Type                   | Content-Type | application/json | name              | internalId     | name        | string       | add-fruit-schema.json|
      | FA003 | Add mango - verify color                     | type=seasonal&color=yellow | none                          | add-fruit-payload.json          | 201        | Created    | color     | yellow     | type              | seasonal      | Content-Type                   | Content-Type | application/json | color             | apiKey         | color       | string       | add-fruit-schema.json|
      | FA004 | Add mango - verify weight type integer       | type=seasonal&color=yellow | none                          | add-fruit-payload.json          | 201        | Created    | weight    | 250        | origin            | India         | Content-Type,X-Fruit-Id        | Content-Type | application/json | weight            | n/a            | weight      | number       | add-fruit-schema.json|
      | FA005 | Add mango - verify price type number         | type=seasonal&color=yellow | none                          | add-fruit-payload.json          | 201        | Created    | pricePerKg| 3.99       | harvestDate       | 2024          | Content-Type                   | Content-Type | application/json | pricePerKg        | n/a            | pricePerKg  | number       | add-fruit-schema.json|
      | FA006 | Add mango - verify inStock boolean           | type=seasonal&color=yellow | none                          | add-fruit-payload.json          | 201        | Created    | inStock   | true       | tags              | tropical      | Content-Type                   | Content-Type | application/json | inStock           | n/a            | inStock     | boolean      | add-fruit-schema.json|
      | FA007 | Add mango - verify nutritionalInfo object    | type=seasonal&color=yellow | none                          | add-fruit-payload.json          | 201        | Created    | status    | success    | nutritionalInfo   | calories      | Content-Type                   | Content-Type | application/json | nutritionalInfo   | n/a            | nutritionalInfo | object   | add-fruit-schema.json|
      | FA008 | Add mango - verify tags array                | type=seasonal&color=yellow | none                          | add-fruit-payload.json          | 201        | Created    | status    | success    | createdAt         | T             | Content-Type                   | Content-Type | application/json | tags              | n/a            | tags        | array        | add-fruit-schema.json|
      | FA009 | Add mango - verify createdAt exists          | type=seasonal&color=yellow | none                          | add-fruit-payload.json          | 201        | Created    | createdAt | NotEmpty   | createdAt         | 2024          | Content-Type                   | Content-Type | application/json | createdAt         | n/a            | createdAt   | string       | add-fruit-schema.json|
      | FA010 | Add mango - from query params file           | fruit-query-params.txt     | none                          | add-fruit-payload.json          | 201        | Created    | status    | success    | message           | successfully  | Content-Type                   | Content-Type | application/json | id                | n/a            | status      | string       | add-fruit-schema.json|
      | FA011 | Add mango - with custom headers              | type=seasonal&color=yellow | X-Request-Id=123,Accept=*/*   | add-fruit-payload.json          | 201        | Created    | status    | success    | name              | Mango         | Content-Type,X-Request-Id      | Content-Type | application/json | message           | n/a            | message     | string       | add-fruit-schema.json|
      | FA012 | Add fruit - verify no sensitive data exposed | type=seasonal&color=yellow | none                          | add-fruit-payload.json          | 201        | Created    | status    | success    | n/a               | n/a           | Content-Type                   | Content-Type | application/json | status            | apiSecret      | status      | string       | add-fruit-schema.json|
      | FA013 | Add fruit - invalid payload empty name       | type=seasonal&color=yellow | none                          | add-fruit-invalid-payload.json  | 400        | Bad Request| n/a       | n/a        | n/a               | n/a           | n/a                            | n/a          | n/a              | n/a               | n/a            | n/a         | n/a          | none                 |
      | FA014 | Add fruit - invalid query params             | type=invalid&color=unknown | none                          | add-fruit-payload.json          | 400        | Bad Request| n/a       | n/a        | n/a               | n/a           | n/a                            | n/a          | n/a              | n/a               | n/a            | n/a         | n/a          | none                 |
